services:
  bot_db:
    container_name: postgres_container
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:${PGDATA}
    ports:
      - "5432:5432"


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  djangogram:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - bot_db


volumes:
  postgres_data:
  pgadmin_data: