services:
  djangogram:
    build:
      context: .
      env_file:
        - .env
      depends_on:
        - bot_db
      ports:
        - "8001:8001"
      command: >
        sh -c "
              python manage.py makemigrations &&
              python manage.py migrate &&
              gunicorn --bind 0.0.0.0:8000 base.wsgi
              "

  bot_db:
    container_name: postgres_container
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"

  nginx:
    build: ./nginx
    ports:
      - 80:80
    command: [ nginx-debug, '-g', 'daemon off;' ]
    depends_on:
      - api

volumes:
  postgres_data: