# Generated by Django 4.2.4 on 2024-04-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangogramm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
