# Generated by Django 4.2.4 on 2024-04-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangogramm", "0002_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="post_comments",
        ),
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="djangogramm.comment"
            ),
        ),
    ]
