# Generated by Django 4.2.4 on 2024-05-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangogramm", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
