# Generated by Django 4.2.4 on 2024-04-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangogramm", "0004_rename_post_comments_comment_post_reference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
