# Generated by Django 4.2.4 on 2024-04-23 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangogramm.models


class Migration(migrations.Migration):

    dependencies = [
        ("djangogramm", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="djangogramm.comment",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                null=True, upload_to=djangogramm.models.get_image_path
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                null=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatars"),
        ),
        migrations.AlterField(
            model_name="user",
            name="biography",
            field=models.TextField(null=True),
        ),
    ]
