# Generated by Django 4.2.4 on 2024-04-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangogramm", "0007_alter_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post_reference",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="djangogramm.post",
            ),
        ),
    ]
