# Generated by Django 4.2.4 on 2024-05-08 13:11

from django.db import migrations, models
import django.db.models.deletion
import djangogramm.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0008_alter_comment_post_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=djangogramm.models.get_image_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='djangogramm.post')),
            ],
        ),
    ]
